export type Channel = {
  id: number;
  category: string;
  channelname: string;
  numvideos: string;
  subscribers: string;
  viewers: string;
};
export const topChannels: Channel[] = [
  {
    id: 1,
    category: 'Food',
    channelname: 'FaZe Rug',
    numvideos: '2.44K',
    subscribers: '27.7M',
    viewers: '9.77B',
  },
  {
    id: 2,
    category: 'Food',
    channelname: 'Nick DiGiovanni',
    numvideos: '414',
    subscribers: '26.4M',
    viewers: '11.78B',
  },
  {
    id: 3,
    category: 'Food',
    channelname: 'BROTHERS VLOG',
    numvideos: '1.83K',
    subscribers: '25M',
    viewers: '15.9B',
  },
  {
    id: 4,
    category: 'Food',
    channelname: 'LukeDidThat',
    numvideos: '392',
    subscribers: '21.5M',
    viewers: '8.8B',
  },
  {
    id: 5,
    category: 'Food',
    channelname: 'Gordon Ramsay',
    numvideos: '1.91K',
    subscribers: '21.4M',
    viewers: '4.41B',
  },
  {
    id: 6,
    category: 'Food',
    channelname: 'HUBA\ud6c4\ubc14',
    numvideos: '850',
    subscribers: '20.8M',
    viewers: '13.8B',
  },
  {
    id: 7,
    category: 'Food',
    channelname: '5-Minute Crafts PLAY',
    numvideos: '7.23K',
    subscribers: '20.1M',
    viewers: '6.5B',
  },
  {
    id: 8,
    category: 'Food',
    channelname: 'Dr Ryan',
    numvideos: '1.93K',
    subscribers: '19.8M',
    viewers: '11.25B',
  },
  {
    id: 9,
    category: 'Food',
    channelname: 'Good Mythical Morning',
    numvideos: '4.09K',
    subscribers: '19.2M',
    viewers: '10.2B',
  },
  {
    id: 10,
    category: 'Food',
    channelname: 'Ivana Alawi',
    numvideos: '236',
    subscribers: '19.1M',
    viewers: '1.7B',
  },
  {
    id: 11,
    category: 'Food',
    channelname: 'T3ddy',
    numvideos: '2.55K',
    subscribers: '18.6M',
    viewers: '3.77B',
  },
  {
    id: 12,
    category: 'Food',
    channelname: 'TRANS TV Official',
    numvideos: '155.22K',
    subscribers: '18.4M',
    viewers: '8.98B',
  },
  {
    id: 13,
    category: 'Music',
    channelname: 'T-Series',
    numvideos: '23.54K',
    subscribers: '294M',
    viewers: '297.69B',
  },
  {
    id: 14,
    category: 'Music',
    channelname: 'BLACKPINK',
    numvideos: '608',
    subscribers: '96.6M',
    viewers: '38.77B',
  },
  {
    id: 15,
    category: 'Music',
    channelname: 'ChuChu TV Nursery Rhymes & Kids Songs',
    numvideos: '868',
    subscribers: '96.2M',
    viewers: '55.05B',
  },
  {
    id: 16,
    category: 'Music',
    channelname: 'HYBE LABELS',
    numvideos: '2.52K',
    subscribers: '77.2M',
    viewers: '39.41B',
  },
  {
    id: 17,
    category: 'Music',
    channelname: 'T-Series Bhakti Sagar',
    numvideos: '30.08K',
    subscribers: '76.2M',
    viewers: '40.01B',
  },
  {
    id: 18,
    category: 'Music',
    channelname: 'Tips Official',
    numvideos: '7.85K',
    subscribers: '75.5M',
    viewers: '47.18B',
  },
  {
    id: 19,
    category: 'Music',
    channelname: 'Justin Bieber',
    numvideos: '249',
    subscribers: '75.4M',
    viewers: '34.86B',
  },
  {
    id: 20,
    category: 'Music',
    channelname: 'Shemaroo Filmi Gaane',
    numvideos: '9.35K',
    subscribers: '72.1M',
    viewers: '32.41B',
  },
  {
    id: 21,
    category: 'Music',
    channelname: 'Infobells - Hindi',
    numvideos: '780',
    subscribers: '69.8M',
    viewers: '42.58B',
  },
  {
    id: 22,
    category: 'Music',
    channelname: 'Canal KondZilla',
    numvideos: '3.32K',
    subscribers: '67.7M',
    viewers: '39.38B',
  },
  {
    id: 23,
    category: 'Music',
    channelname: 'Wave Music',
    numvideos: '20.7K',
    subscribers: '65.7M',
    viewers: '45.43B',
  },
  {
    id: 24,
    category: 'Music',
    channelname: 'YRF',
    numvideos: '4.51K',
    subscribers: '65.6M',
    viewers: '48.04B',
  },
  {
    id: 25,
    category: 'Music',
    channelname: 'EminemMusic',
    numvideos: '198',
    subscribers: '64.9M',
    viewers: '33.92B',
  },
  {
    id: 26,
    category: 'Music',
    channelname: 'Taylor Swift',
    numvideos: '285',
    subscribers: '61M',
    viewers: '39.26B',
  },
  {
    id: 27,
    category: 'Pets',
    channelname: 'Chapitosiki',
    numvideos: '4.88K',
    subscribers: '29.9M',
    viewers: '30.79B',
  },
  {
    id: 28,
    category: 'Pets',
    channelname: 'Dylan Anderson',
    numvideos: '3.07K',
    subscribers: '14.7M',
    viewers: '34.31B',
  },
  {
    id: 29,
    category: 'Pets',
    channelname: 'Troom Troom Indonesia',
    numvideos: '2.38K',
    subscribers: '13.5M',
    viewers: '5.86B',
  },
  {
    id: 30,
    category: 'Pets',
    channelname: 'Troom Troom PT',
    numvideos: '3.22K',
    subscribers: '12.8M',
    viewers: '4.61B',
  },
  {
    id: 31,
    category: 'Pets',
    channelname: 'ViralSnare Rights Management',
    numvideos: '37.71K',
    subscribers: '12.5M',
    viewers: '10.49B',
  },
  {
    id: 32,
    category: 'Pets',
    channelname: 'Animals_Home',
    numvideos: '1.28K',
    subscribers: '12.5M',
    viewers: '6.23B',
  },
  {
    id: 33,
    category: 'Pets',
    channelname: 'Chef Cat ChangAn ',
    numvideos: '596',
    subscribers: '10.7M',
    viewers: '7.19B',
  },
  {
    id: 34,
    category: 'Pets',
    channelname: 'EODRIOZOLA',
    numvideos: '1.44K',
    subscribers: '10.5M',
    viewers: '1.17B',
  },
  {
    id: 35,
    category: 'Pets',
    channelname: 'deHakims channel',
    numvideos: '3.16K',
    subscribers: '10.2M',
    viewers: '2.14B',
  },
  {
    id: 36,
    category: 'Pets',
    channelname: 'Sirf Shreyansh',
    numvideos: '417',
    subscribers: '9.04M',
    viewers: '4.67B',
  },
  {
    id: 37,
    category: 'Pets',
    channelname: 'Wildlife Adventure In \u0939\u093f\u0928\u094d\u0926\u0940',
    numvideos: '933',
    subscribers: '8.83M',
    viewers: '4.06B',
  },
  {
    id: 38,
    category: 'Pets',
    channelname: 'BitesFrome',
    numvideos: '632',
    subscribers: '7.72M',
    viewers: '985.42M',
  },
  {
    id: 39,
    category: 'Pets',
    channelname: 'Wilderness TV',
    numvideos: '171',
    subscribers: '7.71M',
    viewers: '2.33B',
  },
  {
    id: 40,
    category: 'Pets',
    channelname: 'Maori Blue',
    numvideos: '1.33K',
    subscribers: '7.67M',
    viewers: '4.42B',
  },
  {
    id: 41,
    category: 'Pets',
    channelname: 'Play TOP',
    numvideos: '331',
    subscribers: '6.75M',
    viewers: '305.8M',
  },
  {
    id: 42,
    category: 'Pets',
    channelname: 'Viros',
    numvideos: '3.2K',
    subscribers: '6.65M',
    viewers: '1.07B',
  },
  {
    id: 43,
    category: 'Sports',
    channelname: 'UR Cristiano ',
    numvideos: '102',
    subscribers: '75.1M',
    viewers: '844.09M',
  },
  {
    id: 44,
    category: 'Sports',
    channelname: 'Celine Dept ',
    numvideos: '1.47K',
    subscribers: '47.6M',
    viewers: '36.79B',
  },
  {
    id: 45,
    category: 'Sports',
    channelname: 'Jesser ',
    numvideos: '1.49K',
    subscribers: '29.5M',
    viewers: '7.37B',
  },
  {
    id: 46,
    category: 'Sports',
    channelname: 'NBA ',
    numvideos: '68.5K',
    subscribers: '23.1M',
    viewers: '15.82B',
  },
  {
    id: 47,
    category: 'Sports',
    channelname: 'FIFA ',
    numvideos: '11.84K',
    subscribers: '23.1M',
    viewers: '7.5B',
  },
  {
    id: 48,
    category: 'Sports',
    channelname: 'Sidemen ',
    numvideos: '414',
    subscribers: '22.3M',
    viewers: '7.01B',
  },
  {
    id: 49,
    category: 'Sports',
    channelname: 'FC Barcelona ',
    numvideos: '13.41K',
    subscribers: '22.2M',
    viewers: '5.4B',
  },
  {
    id: 50,
    category: 'Sports',
    channelname: 'Jake Paul ',
    numvideos: '1.48K',
    subscribers: '20.9M',
    viewers: '7.78B',
  },
  {
    id: 51,
    category: 'Sports',
    channelname: 'UFC ',
    numvideos: '20.59K',
    subscribers: '20.5M',
    viewers: '9.77B',
  },
  {
    id: 52,
    category: 'Sports',
    channelname: 'z\u00e9TV ',
    numvideos: '10.72K',
    subscribers: '19.3M',
    viewers: '2.92B',
  },
  {
    id: 53,
    category: 'Sports',
    channelname: 'House of Highlights ',
    numvideos: '20.97K',
    subscribers: '17.3M',
    viewers: '14.53B',
  },
  {
    id: 54,
    category: 'Sports',
    channelname: 'Real Madrid ',
    numvideos: '7.61K',
    subscribers: '17.3M',
    viewers: '3.19B',
  },
  {
    id: 55,
    category: 'Sports',
    channelname: 'W2S ',
    numvideos: '653',
    subscribers: '16.3M',
    viewers: '4.85B',
  },
  {
    id: 56,
    category: 'Sports',
    channelname: 'Paul Ferrer Z ',
    numvideos: '1.45K',
    subscribers: '15.9M',
    viewers: '4.3B',
  },
  {
    id: 57,
    category: 'Travel',
    channelname: 'Marusya Outdoors',
    numvideos: '110',
    subscribers: '20.2M',
    viewers: '8.65B',
  },
  {
    id: 58,
    category: 'Travel',
    channelname: 'Brincando com o Rafael',
    numvideos: '408',
    subscribers: '11.8M',
    viewers: '4.74B',
  },
  {
    id: 59,
    category: 'Travel',
    channelname: 'Yes Theory',
    numvideos: '422',
    subscribers: '9.46M',
    viewers: '1.19B',
  },
  {
    id: 60,
    category: 'Travel',
    channelname: 'PHD - Ph\u01b0\u01a1ng H\u1eefu D\u01b0\u1ee1ng',
    numvideos: '1.23K',
    subscribers: '8.82M',
    viewers: '5.19B',
  },
];

export type VideoItem = {
  id: number;
  title: string;
  url: string;
  thumbnail: string;
  duration: string;
  uploaded: string;
  views: number;
};

export type VideoSection = {
  section: string; // e.g., "hoops", "kananGill", etc.
  videos: VideoItem[];
};

export type VideoData = VideoSection[];

export const homeThumbnails: VideoData = [
  {
    section: 'hoops',
    videos: [
      {
        id: 1,
        title: 'Best NBA Plays of 2025 But They Get Increasingly More Mind-Blowing ! 🤯',
        url: 'https://www.youtube.com/watch?v=hbPEhfo7iFs',
        thumbnail: 'https://i.ytimg.com/vi/hbPEhfo7iFs/mqdefault.jpg',
        duration: '13:45',
        uploaded: 'Today',
        views: 2286,
      },
      {
        id: 2,
        title: 'NBA "Carry My Team!" 🔥 MOMENTS',
        url: 'https://www.youtube.com/watch?v=7dumbK5u7ww',
        thumbnail: 'https://i.ytimg.com/vi/7dumbK5u7ww/mqdefault.jpg',
        duration: '14:40',
        uploaded: 'Today',
        views: 9801,
      },
      {
        id: 3,
        title: "LaMelo Ball's FLASHY 2025 Highlights - Street-Baller 🔥",
        url: 'https://www.youtube.com/watch?v=Nk4KSTHWPJU',
        thumbnail: 'https://i.ytimg.com/vi/Nk4KSTHWPJU/mqdefault.jpg',
        duration: '28:11',
        uploaded: '1 day ago',
        views: 7331,
      },
      {
        id: 4,
        title: 'NBA "Try Not to Cry!" Moments',
        url: 'https://www.youtube.com/watch?v=KRRKfiDWxxw',
        thumbnail: 'https://i.ytimg.com/vi/KRRKfiDWxxw/mqdefault.jpg',
        duration: '15:39',
        uploaded: '1 day ago',
        views: 37659,
      },
      {
        id: 5,
        title: 'The World is NOT Ready for Victor Wembanyama 2.0 ! 🔥 Revenge Season',
        url: 'https://www.youtube.com/watch?v=qwJ6W3bGYBs',
        thumbnail: 'https://i.ytimg.com/vi/qwJ6W3bGYBs/mqdefault.jpg',
        duration: '13:13',
        uploaded: '2 days ago',
        views: 17904,
      },
      {
        id: 6,
        title: 'NBA "Memory Glitch" MOMENTS',
        url: 'https://www.youtube.com/watch?v=loLVQhJ2Qtk',
        thumbnail: 'https://i.ytimg.com/vi/loLVQhJ2Qtk/mqdefault.jpg',
        duration: '20:30',
        uploaded: '2 days ago',
        views: 54267,
      },
      {
        id: 7,
        title: 'NBA "Look at the Scoreboard!" 😱 MOMENTS',
        url: 'https://www.youtube.com/watch?v=KLn1jRs0pcc',
        thumbnail: 'https://i.ytimg.com/vi/KLn1jRs0pcc/mqdefault.jpg',
        duration: '15:26',
        uploaded: '3 days ago',
        views: 29825,
      },
      {
        id: 8,
        title: 'Shai Gilgeous-Alexander - Master of The Mid-Range! 🔥',
        url: 'https://www.youtube.com/watch?v=nctPRqEOyC4',
        thumbnail: 'https://i.ytimg.com/vi/nctPRqEOyC4/mqdefault.jpg',
        duration: '13:01',
        uploaded: '3 days ago',
        views: 26373,
      },
      {
        id: 9,
        title: 'NBA "Impossible!" MOMENTS',
        url: 'https://www.youtube.com/watch?v=cKrmCKAK5fI',
        thumbnail: 'https://i.ytimg.com/vi/cKrmCKAK5fI/mqdefault.jpg',
        duration: '17:00',
        uploaded: '4 days ago',
        views: 70657,
      },
      {
        id: 10,
        title: 'The Biggest Comebacks in NBA History!',
        url: 'https://www.youtube.com/watch?v=DIUOFu_5Rt4',
        thumbnail: 'https://i.ytimg.com/vi/DIUOFu_5Rt4/mqdefault.jpg',
        duration: '20:01',
        uploaded: '4 days ago',
        views: 51562,
      },
    ],
  },
  {
    section: 'kananGill',
    videos: [
      {
        id: 1,
        title: 'Is This It? - Full Comedy Special | Kanan Gill 2023',
        url: 'https://www.youtube.com/watch?v=fh0Ru6LjBAY',
        thumbnail: 'https://i.ytimg.com/vi/fh0Ru6LjBAY/mqdefault.jpg',
        duration: '1:59:57',
        uploaded: '1 year ago',
        views: 2868064,
      },
      {
        id: 2,
        title: 'Kanan Gill - Siblings - Stand Up Comedy',
        url: 'https://www.youtube.com/watch?v=Kb1fFLkbPao',
        thumbnail: 'https://i.ytimg.com/vi/Kb1fFLkbPao/mqdefault.jpg',
        duration: '2:39',
        uploaded: '8 years ago',
        views: 4371496,
      },
      {
        id: 3,
        title: 'Kanan Gill - Relationships, Traps and Blackheads - Keep It Real',
        url: 'https://www.youtube.com/watch?v=XJCrR9HcH9Y',
        thumbnail: 'https://i.ytimg.com/vi/XJCrR9HcH9Y/mqdefault.jpg',
        duration: '4:48',
        uploaded: '8 years ago',
        views: 3743917,
      },
      {
        id: 4,
        title: 'Kanan Gill - Explaining Technology To Parents - Keep It Real',
        url: 'https://www.youtube.com/watch?v=2wzPF_Xw7WU',
        thumbnail: 'https://i.ytimg.com/vi/2wzPF_Xw7WU/mqdefault.jpg',
        duration: '3:11',
        uploaded: '8 years ago',
        views: 3020533,
      },
      {
        id: 5,
        title: 'Kya Kehna Review - Bloopers and Deleted Scenes',
        url: 'https://www.youtube.com/watch?v=iXUXf9_0cjo',
        thumbnail: 'https://i.ytimg.com/vi/iXUXf9_0cjo/mqdefault.jpg',
        duration: '4:40',
        uploaded: '10 years ago',
        views: 685784,
      },
      {
        id: 6,
        title: 'Disco Dancer Review - Bloopers and Deleted Scenes',
        url: 'https://www.youtube.com/watch?v=1a1ZTfDzioU',
        thumbnail: 'https://i.ytimg.com/vi/1a1ZTfDzioU/mqdefault.jpg',
        duration: '3:01',
        uploaded: '10 years ago',
        views: 483332,
      },
      {
        id: 7,
        title: '(BONUS!) MOST DANCE EVER - Disco Dancer Review',
        url: 'https://www.youtube.com/watch?v=YCEwVXb9eyI',
        thumbnail: 'https://i.ytimg.com/vi/YCEwVXb9eyI/mqdefault.jpg',
        duration: '6:37',
        uploaded: '10 years ago',
        views: 3335668,
      },
      {
        id: 8,
        title: 'MOST BOLLYWOOD EVER - Dilwale Dulhaniya Le Jayenge Review',
        url: 'https://www.youtube.com/watch?v=TOZyX3bv2Hc',
        thumbnail: 'https://i.ytimg.com/vi/TOZyX3bv2Hc/mqdefault.jpg',
        duration: '11:46',
        uploaded: '10 years ago',
        views: 6042273,
      },
      {
        id: 9,
        title: 'This is what we do. 4 Friendship.',
        url: 'https://www.youtube.com/watch?v=4BnXAXuTID4',
        thumbnail: 'https://i.ytimg.com/vi/4BnXAXuTID4/mqdefault.jpg',
        duration: '0:34',
        uploaded: '11 years ago',
        views: 4162913,
      },
      {
        id: 10,
        title: 'Rudraksh - Bloopers and Deleted Scenes',
        url: 'https://www.youtube.com/watch?v=mcutrjiE6jM',
        thumbnail: 'https://i.ytimg.com/vi/mcutrjiE6jM/mqdefault.jpg',
        duration: '3:05',
        uploaded: '11 years ago',
        views: 421220,
      },
    ],
  },
];

export type AnalyticsData = {
  id: string;
  title: string;
  publishedAt: Date;
  views: number;
};

export const analyticsData: AnalyticsData[] = [
  {
    id: 'dQw4w9WgXcQ',
    title: 'How to Master JavaScript in 30 Days',
    publishedAt: new Date('2024-12-15T14:30:00Z'),
    views: 892547,
  },
  {
    id: 'Xvs892k9XsQ',
    title: 'The Ultimate Guide to React Components',
    publishedAt: new Date('2024-12-12T09:15:32Z'),
    views: 456789,
  },
  {
    id: 'abc123DefGh',
    title: 'CSS Grid vs Flexbox - Which Should You Use?',
    publishedAt: new Date('2024-12-08T16:45:21Z'),
    views: 234567,
  },
  {
    id: 'NodeJs4Ever',
    title: 'Building APIs with Node.js and Express',
    publishedAt: new Date('2024-12-05T11:20:15Z'),
    views: 678901,
  },
  {
    id: 'PythonMagic1',
    title: 'Python Data Science Fundamentals',
    publishedAt: new Date('2024-12-01T08:33:44Z'),
    views: 345678,
  },
  {
    id: 'SQLqueryPro',
    title: 'Advanced SQL Queries Every Developer Should Know',
    publishedAt: new Date('2024-11-28T13:12:09Z'),
    views: 567890,
  },
  {
    id: 'DevOpsTools5',
    title: 'Docker for Beginners - Complete Tutorial',
    publishedAt: new Date('2024-11-25T10:45:33Z'),
    views: 789012,
  },
  {
    id: 'WebDesign99',
    title: 'Modern Web Design Principles',
    publishedAt: new Date('2024-11-22T15:22:18Z'),
    views: 123456,
  },
  {
    id: 'GitVersion1',
    title: 'Git and GitHub - Version Control Made Easy',
    publishedAt: new Date('2024-11-19T12:08:47Z'),
    views: 445566,
  },
  {
    id: 'TypeScript7',
    title: 'Why TypeScript is Better Than JavaScript',
    publishedAt: new Date('2024-11-16T09:30:26Z'),
    views: 887799,
  },
  {
    id: 'MobileFirst8',
    title: 'Mobile-First Development Strategy',
    publishedAt: new Date('2024-11-13T14:55:12Z'),
    views: 334455,
  },
  {
    id: 'CloudAWS456',
    title: 'AWS for Beginners - Complete Guide',
    publishedAt: new Date('2024-11-10T11:17:39Z'),
    views: 556677,
  },
  {
    id: 'SecurityWeb2',
    title: 'Web Security Best Practices',
    publishedAt: new Date('2024-11-07T16:42:55Z'),
    views: 778899,
  },
  {
    id: 'AlgorithmsFun',
    title: 'Data Structures and Algorithms Simplified',
    publishedAt: new Date('2024-11-04T08:24:13Z'),
    views: 667788,
  },
  {
    id: 'APIdesign101',
    title: 'RESTful API Design Best Practices',
    publishedAt: new Date('2024-11-01T13:37:48Z'),
    views: 445566,
  },
  {
    id: 'TestingCode3',
    title: 'Unit Testing in JavaScript',
    publishedAt: new Date('2024-10-29T10:19:25Z'),
    views: 223344,
  },
  {
    id: 'Performance4',
    title: 'Frontend Performance Optimization',
    publishedAt: new Date('2024-10-26T15:03:17Z'),
    views: 556677,
  },
  {
    id: 'DatabaseOpt5',
    title: 'Database Optimization Techniques',
    publishedAt: new Date('2024-10-23T09:48:52Z'),
    views: 334455,
  },
  {
    id: 'MachineLrn6',
    title: 'Machine Learning with Python',
    publishedAt: new Date('2024-10-20T14:15:29Z'),
    views: 889900,
  },
  {
    id: 'BlockchainABC',
    title: 'Blockchain Development for Beginners',
    publishedAt: new Date('2024-10-17T11:52:41Z'),
    views: 112233,
  },
  {
    id: 'MicroServices7',
    title: 'Microservices Architecture Explained',
    publishedAt: new Date('2024-10-14T16:28:06Z'),
    views: 445566,
  },
  {
    id: 'GraphQLnow8',
    title: 'GraphQL vs REST API',
    publishedAt: new Date('2024-10-11T08:14:33Z'),
    views: 667788,
  },
  {
    id: 'KubernetesK8',
    title: 'Kubernetes for Developers',
    publishedAt: new Date('2024-10-08T12:41:18Z'),
    views: 778899,
  },
  {
    id: 'ReactNative9',
    title: 'React Native Mobile Development',
    publishedAt: new Date('2024-10-05T15:07:44Z'),
    views: 556677,
  },
  {
    id: 'Vue3Update0',
    title: 'Vue 3 New Features and Updates',
    publishedAt: new Date('2024-10-02T09:23:51Z'),
    views: 334455,
  },
  {
    id: 'FullStackDev',
    title: 'Full Stack Development Roadmap 2024',
    publishedAt: new Date('2024-09-29T13:56:27Z'),
    views: 991122,
  },
  {
    id: 'CyberSecure1',
    title: 'Cybersecurity for Developers',
    publishedAt: new Date('2024-09-26T10:32:15Z'),
    views: 445566,
  },
  {
    id: 'MongoDBpro2',
    title: 'MongoDB Advanced Queries',
    publishedAt: new Date('2024-09-23T14:18:42Z'),
    views: 223344,
  },
  {
    id: 'RedisCache33',
    title: 'Redis Caching Strategies',
    publishedAt: new Date('2024-09-20T11:45:08Z'),
    views: 556677,
  },
  {
    id: 'ElasticSearch4',
    title: 'Elasticsearch for Beginners',
    publishedAt: new Date('2024-09-17T16:29:54Z'),
    views: 334455,
  },
];
